### ISSUE TITLE
 limit_type=1 ist meines Erachtens falsch

### ISSUE THREAD

**Issue by zfrank2601** [Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM#1]
limit_type=1 ist meines Erachtens falsch da dort der "relative" Wert gesetzt wird in %. Es müsste aber absolute gesetzt werden.
Kann das jemand verifizieren? Ich habe es bei mir jetzt angepasst und es funktioniert dann. (Mit abgewandelten Script speziell für Emlog)

Laut Quellcode:

    AbsolutNonPersistent = 0x0000, // 0
    RelativNonPersistent = 0x0001, // 1
    AbsolutPersistent = 0x0100, // 256
    RelativPersistent = 0x0101 // 257

**Comment by Selbstbau-PV** [comment]
Danke, wir haben es ausprobiert und konnten bestätigen, wurde angepasst.

https://github.com/Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM/commit/cc4935acb5c229b332b03ac1edb99026db163c30
