### ISSUE TITLE
Python Script change for Shelly 3EM Pro API

### ISSUE THREAD

**Issue by MarkusPVHM** [Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM#16]
Hello, it would be very helpful for me,  if sombody could modify this python script for a shelly 3EM pro, which has a different API than shelly 3EM.

Thanks in advance Markus

**Comment by kthemall** [comment]
# Nimmt Daten von der Shelly 3EM Rest-API und übersetzt sie in ein json-Format
        phase_a = requests.get(f'http://{shelly_ip}/rpc/EM.GetStatus?id=0', headers={'Content-Type': 'application/json'}).json()['a_act_power']
        phase_b = requests.get(f'http://{shelly_ip}/rpc/EM.GetStatus?id=0', headers={'Content-Type': 'application/json'}).json()['b_act_power']
        phase_c = requests.get(f'http://{shelly_ip}/rpc/EM.GetStatus?id=0', headers={'Content-Type': 'application/json'}).json()['c_act_power']
 

 
 

Gesendet: Dienstag, 06. Juni 2023 um 14:14 Uhr
Von: "MarkusPVHM" ***@***.***>
An: "Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM] Python Script change for Shelly 3EM Pro API (Issue #16)


 

Hello, it would be very helpful for me, if sombody could modify this python script for a shelly 3EM pro, which has a different API than shelly 3EM.

Thanks in advance Markus

**Comment by greymda** [comment]
@MarkusPVHM can you confirm this works? cheers

**Comment by MarkusPVHM** [comment]
> @MarkusPVHM can you confirm this works? cheers

Yeah, it works perfekt with shelly 3EM Pro and older OPENDTU Firmwares

But it is not working any more with newer OPENDTU Firmware, they changed the API again....
