### ISSUE TITLE
Änderungen in aktuelle OpenDTU-Api

### ISSUE THREAD

**Issue by zfrank2601** [Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM#2]
In der aktuellen OpenDTU-Api hat sich das json etwas geändert.  DC/AC kam mit dazu.
Müsste angepasst werden:

    power_dc    = r['inverters'][0]['DC']['0']['Power DC']['v']  # Lieferung DC vom Panel
    power       = r['inverters'][0]['AC']['0']['Power']['v'] # Abgabe BKW AC in Watt

**Comment by zfrank2601** [comment]
@nemesis2912 gute Hinweis, das konnte ich nicht verifizieren mit 1 String + HM350.

**Comment by Selbstbau-PV** [comment]
Danke wurde im letzen Commit angepasst.
https://github.com/Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM/commit/b1e963174cee4074a9b8077516c52123f8309aec
