### ISSUE TITLE
Überlegungen zur Berechnung des zu setzenden Power Limits

### ISSUE THREAD

**Issue by Rayn0r** [Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM#5]
Ich hab mir den Code mal angesehen und habe ein paar Verständnisfragen und nen Vorschlag wie man das Ganze vereinfachen könnte.
Bitte lasst mich wissen, was ihr dazu meint.

 Was in Zeile 52 passieren soll ist mir nicht ganz klar. 
 * Warum kann man die Leistung auf `maximum_wr` setzen wenn `altes_limit >= maximum_wr` ist?
 * Vom Wert `grid_sum` ist die erzeugte Energie (`power`) der Anlage bereits abgezogen. Um den tatsächlichen Verbrauch zu bestimmen, muss man beide Werte wieder addieren. Die Bedingung `grid_sum >= maximum_wr` ist also grundsätzlich verkehrt und würde anders als gewünscht unter Umständen doch etwas einspeisen.
 * Da "setpoint" auf jeden Fall `0` ist, ist die Bedingung `setpoint >= maximum_wr` nie erfüllt. (siehe Zeile 32)

Ich denke, dass man alles zwischen Zeile 51 und 64 durch Folgendes ersetzen kann.
```
aktuellerverbauch = grid_sum + power

if aktuellerverbauch >= maximum_wr:
    setpoint = maximum_wr
    print(f"setpoint auf Maximum ({maximum_wr}W) gesetzt.")
else:
    setpoint = aktuellerverbauch
    print(f"setpoint auf {aktuellerverbauch}W gesetzt.")
```

**Comment by karrenbauer** [comment]
..ja, macht irgendwie mehr Sinn, bin aber leider in Python nur Anfänger....bin schon froh, wenn ich ein Script zum laufen bekomme...

**Comment by Rayn0r** [comment]
Wenn die DTU keine Werte unter 10W akzeptiert, dann sollte das Ganze besser so aussehen:
```
aktuellerverbauch = grid_sum + power

if aktuellerverbauch >= maximum_wr:
    setpoint = maximum_wr
    print(f"setpoint auf Maximum ({maximum_wr}W) gesetzt.")
else:
    if aktuellerverbauch < 10: 
        aktuellerverbauch = 10
    setpoint = aktuellerverbauch
    print(f"setpoint auf {aktuellerverbauch}W gesetzt.")
```

**Comment by karrenbauer** [comment]
musste warten bis es dunkel wird, hatte den Script noch etwas abgeändert, bleibt nicht hängen, aber:
sollte ab Zeile 79 bei:

    if setpoint == 0: setpoint = grid_sum
    if not reachable: setpoint = maximum_wr , print("_ WR1 not reachable ______ ",setpoint)

nicht maximum_wr ausgegeben werden?
Code im Anhang...
![2023 04 26 21 11](https://user-images.githubusercontent.com/14368481/234680824-7ee5e074-ae0a-4905-a15b-15b63beec385.JPG)
[nulleinspeisung_1.2711.zip](https://github.com/Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM/files/11336542/nulleinspeisung_1.2711.zip)

**Comment by karrenbauer** [comment]
hab´s jetzt irgendwie hin bekommen mit:
if not reachable: setpoint = maximum_wr
print("_ WR1 not reachable _____ SP: ",setpoint, maximum_wr)

warum weiss ich aber auch nicht so genau, Python iss irgendwie "empfindlich" ...

**Comment by Selbstbau-PV** [comment]
Danke für die Hinweise. Die Funktionsweise wurde vollständig übernommen von https://gitlab.com/p3605/hoymiles-tarnkappe
Wenn du das Limit vom aktuellen Verbrauch, statt dem letzten Limit abhängig machen möchtest, kannst du in [#L43](https://github.com/Selbstbau-PV/Selbstbau-PV-Hoymiles-nulleinspeisung-mit-OpenDTU-und-Shelly3EM/blob/main/nulleinspeisung.py#L43) `altes_limit` durch `power` ersetzen. Dann werden Einspeisungen eher vermieden, als dass sie nur "abgefedert" werden. Auch kann man die 5 W als Toleranz justieren.

Das Skript wurde mal ein wenig aufgeräumt und übersichtlicher gestaltet. Ein paar potentielle Gründe für Instabilität wurden auch eliminiert. Versuch es gerne mal mit der neuesten Version.
Vielleicht ist es auch vorteilhaft, es wie im Wiki beschrieben als Systemd-Service zu installieren: https://selbstbau-pv.de/wissensbasis/nulleinspeisung-hoymiles-hm-1500-mit-opendtu-python-steuerung/

LG,
SBPV

**Comment by Rayn0r** [comment]
@Selbstbau-PV 
Zeile 41 macht mir noch Sorgen. Die beiden Werte dort könnten nicht definiert sein, wenn zum Start des Scripts einer oder beide Geräte nicht erreichbar sind. Das Verschieben hinter `if reachable:` würde es sicher machen.
Dann ist `if reachable:` keine ausreichende Bedingung mehr um weiterzumachen, weil die beiden Abfragen jetzt in getrennten `try/except` Blöcken stehen. Im `except` beider könnte aber ein `reachable = false` weiterhelfen.

Was denkst Du?

**Comment by Rayn0r** [comment]
Sollte man noch den Fall betrachten, bei dem der Shelly nicht erreichbar ist, die OpenDTU aber dennoch?
Ist es dann sinnvoll die Leistungsabgabe auf ein vorher festgelegtes Maximum zu begrenzen?
